// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using PrecisionFullCoilHMI.Data;

#nullable disable

namespace PrecisionFullCoilHMI.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("PrecisionFullCoilHMI.Models.Job", b =>
                {
                    b.Property<short>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("smallint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<short>("Id"));

                    b.Property<short>("Bead")
                        .HasColumnType("smallint");

                    b.Property<short>("CleatEdges")
                        .HasColumnType("smallint");

                    b.Property<short>("Cleats")
                        .HasColumnType("smallint");

                    b.Property<short>("Connector")
                        .HasColumnType("smallint");

                    b.Property<short>("DuctType")
                        .HasColumnType("smallint");

                    b.Property<short>("Gauge")
                        .HasColumnType("smallint");

                    b.Property<short>("HoleDie")
                        .HasColumnType("smallint");

                    b.Property<short>("HoleSize")
                        .HasColumnType("smallint");

                    b.Property<short>("Insulation")
                        .HasColumnType("smallint");

                    b.Property<short>("JobNumber")
                        .HasColumnType("smallint");

                    b.Property<DateTime>("LastUpdateDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<short>("Lock")
                        .HasColumnType("smallint");

                    b.Property<short>("PinSpacing")
                        .HasColumnType("smallint");

                    b.Property<short>("Quantity")
                        .HasColumnType("smallint");

                    b.Property<int>("RecipeId")
                        .HasColumnType("integer");

                    b.Property<short>("Sealant")
                        .HasColumnType("smallint");

                    b.Property<float>("SideA")
                        .HasColumnType("real");

                    b.Property<short>("SideAHoles")
                        .HasColumnType("smallint");

                    b.Property<float>("SideB")
                        .HasColumnType("real");

                    b.Property<short>("SideBHoles")
                        .HasColumnType("smallint");

                    b.HasKey("Id");

                    b.HasIndex("RecipeId");

                    b.ToTable("Jobs");
                });

            modelBuilder.Entity("PrecisionFullCoilHMI.Models.Recipe", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("LastUpdateDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<short>("NumberOfJobs")
                        .HasColumnType("smallint");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Recipes");
                });

            modelBuilder.Entity("PrecisionFullCoilHMI.Models.Tag", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int?>("ArrayEnd")
                        .HasColumnType("integer");

                    b.Property<int?>("ArrayStart")
                        .HasColumnType("integer");

                    b.Property<int>("Definition")
                        .HasColumnType("integer");

                    b.Property<string>("Description")
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)");

                    b.Property<bool>("IsArray")
                        .HasColumnType("boolean");

                    b.Property<int>("MaintenancePurpose")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("NodeId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<bool>("Subscribe")
                        .HasColumnType("boolean");

                    b.Property<string>("UnitOfMeasurement")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.HasKey("Id");

                    b.ToTable("Tags");
                });

            modelBuilder.Entity("PrecisionFullCoilHMI.Models.Job", b =>
                {
                    b.HasOne("PrecisionFullCoilHMI.Models.Recipe", "Recipe")
                        .WithMany("Jobs")
                        .HasForeignKey("RecipeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Recipe");
                });

            modelBuilder.Entity("PrecisionFullCoilHMI.Models.Recipe", b =>
                {
                    b.Navigation("Jobs");
                });
#pragma warning restore 612, 618
        }
    }
}
